Repository zestedesavoir/zds-site, pull requests merged in 2018-12, with the labels that each got.

#5121 Corrige "Aller à la page" dans la pagination (fix #5108)
  templates/misc/paginator.html
Labels: Bloquant, C-Front, S-BUG

#5120 Corrige les filtres de la recherche (fix #5107)
  templates/searchv2/search.html
  zds/searchv2/forms.py
Labels: Bloquant, C-Front, S-BUG

#5123 Améliore le bandeau sur l'utilisation des cookies (fix #5074)
  assets/scss/components/_cookies-banner.scss
  templates/base.html
Labels: C-Front, S-Évolution

#5060 Ajout de l'option --speed pour gulp
  Gulpfile.js
  package.json
Labels: C-DevelopmentEnv

#5125 Supprime une propriété CSS causant des problèmes (fix #5124)
  assets/scss/layout/_content.scss
Labels: Bloquant, C-Front, S-BUG

#5130 Corrige un possible malentendu en lisant la phrase
  scripts/install_zds.sh
Labels: C-DevelopmentEnv

#5129 Colorise `install_zds.sh` pour mieux suivre l'évolution de la commande
  scripts/install_zds.sh
Labels: C-DevelopmentEnv

#5135 Corrige l'affichage des blocs de code dans les listes (fix #5004)
  assets/scss/base/_content.scss
Labels: C-Front, S-BUG

#5117 Change md export
  templates/tutorialv2/export/content.md
  zds/tutorialv2/models/database.py
  zds/tutorialv2/publication_utils.py
  zds/utils/templatetags/emarkdown.py
  zds/utils/templatetags/tests/tests_emarkdown.py
Labels: C-Back, S-BUG

#5139 Revert "Respect des nouvelles norme d'import SASS"
  assets/scss/main.scss
  assets/scss/zmd.scss
Labels: Bloquant, C-Front, S-BUG

#5131 core: update katex @ 0.10.0 to fit with new css
  package.json
  templates/base.html
  yarn.lock
Labels: C-Front

#5158 Fix problem with unordered data
  zds/tutorialv2/views/published.py
Labels: Bloquant, C-Back, S-BUG

#5161 Accessibility enhancement
  templates/tutorialv2/stats/index.html
Labels: C-Front, S-Évolution

#5170 Ajout "voir les stats" sur la version en ligne
  templates/tutorialv2/view/content_online.html
Labels: C-Front, S-Évolution

#5169 Support de la commande "--speed" pour watch
  Gulpfile.js
Labels: C-DevelopmentEnv, S-BUG

#5177 Fix #5154: Support du clipboard (coller) pour Edge
  assets/js/editor.js
Labels: Bloquant, C-Front, S-BUG

#5173 Fix #5164: Corrige l'ordre des filtres pour la liste des contenus
  zds/tutorialv2/views/contents.py
Labels: C-Front, S-Régression

#5140 Ameliore les balises spoiler
  assets/js/spoiler.js
  assets/scss/base/_content.scss
Labels: Bloquant, C-Front, S-Régression

#5160 Supprime le fichier contenant les faux accès à l'API Google Analytics
  api_analytics_secrets.json
  doc/source/back-end/contents.rst
Labels: Bloquant, C-Back

#5184 Fix #4459 : Ajout d'une marge sous le bouton envoyer
  assets/scss/components/_topic-message.scss
Labels: C-Front, S-Évolution
