Repository zestedesavoir/zds-site, pull requests merged in 2018-03, with the labels that each got.

#4880 Corrige l'indication du temps de lecture estimé quand il est inférieur à une minute
  zds/tutorialv2/views/published.py
Labels: C-Back

#4891 Rotation des logs django en prod
  zds/settings/prod.py
Labels: C-Infra

#4907 Corrige l'affiche du nom du site sur mobile
  assets/scss/layout/_header.scss
Labels: C-Front, S-BUG

#4909 CSS pour le ping
  assets/scss/base/_content.scss
Labels: C-Front

#4912 Affiche le code source avec de belles couleurs
  templates/base.html
Labels: C-Front

#4913 Empêche le code source de déborder de la page
  assets/scss/base/_content.scss
Labels: C-Front, S-BUG

#4916 Corrige le CSS du bloc de code
  assets/scss/base/_content.scss
Labels: C-Front
