Repository zestedesavoir/zds-site, pull requests merged in 2018-09, with the labels that each got.

#5019 Vérifie si l'utilisateur a une adresse mail avant de lui envoyer un mail.
  zds/notification/models.py
  zds/notification/tests/tests_tricky.py
Labels: Bloquant, C-Back, S-BUG

#5008 Création de l'API des images
  doc/source/api.rst
  doc/source/utils/fixture_loaders.rst
  fixtures/oauth_applications.yaml
  templates/gallery/base.html
  templates/gallery/gallery/details.html
  templates/gallery/gallery/list.html
  templates/gallery/image/edit.html
  zds/api/key_constructor.py
  zds/api/urls.py
  zds/api/views.py
  zds/featured/tests.py
  zds/gallery/api/__init__.py
  zds/gallery/api/permissions.py
  zds/gallery/api/serializers.py
  zds/gallery/api/tests.py
  zds/gallery/api/urls.py
  zds/gallery/api/views.py
  zds/gallery/forms.py
  zds/gallery/managers.py
  zds/gallery/migrations/0005_auto_20180816_2256.py
  zds/gallery/mixins.py
  zds/gallery/models.py
  zds/gallery/tests/tests_forms.py
  zds/gallery/tests/tests_views.py
  zds/gallery/urls.py
  zds/gallery/views.py
  zds/member/tests/tests_models.py
  zds/member/tests/tests_views.py
  zds/mp/api/views.py
  zds/notification/tests/tests_tricky.py
  zds/searchv2/tests/tests_models.py
  zds/searchv2/tests/tests_utils.py
  zds/searchv2/tests/tests_views.py
  zds/tutorialv2/api/tests.py
  zds/tutorialv2/tests/__init__.py
  zds/tutorialv2/tests/tests_lists.py
  zds/tutorialv2/tests/tests_models.py
  zds/tutorialv2/tests/tests_move.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_utils.py
  zds/tutorialv2/tests/tests_views.py
  zds/utils/management/tests.py
  zds/utils/templatetags/get_item.py
  zds/utils/templatetags/tests/tests_topbar_tags.py
Labels: Bloquant, C-Back, S-Évolution

#5056 Corrige le clignotement sous Chrome
  Gulpfile.js
Labels: C-Front, S-BUG

#5001 Améliore la documentation et l'installation
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
  assets/tex/coverpage.pdf
  assets/tex/template.tex
  doc/source/conf.py
  doc/source/contributing.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/install/backend-linux-install.rst
  doc/source/install/extra-deploy-in-production.rst
  doc/source/install/extra-install-es.rst
  doc/source/install/extra-install-frontend.rst
  doc/source/install/extra-install-latex.rst
  doc/source/install/extra-zmd.rst
  doc/source/install/install-linux.rst
  doc/source/install/install-osx.rst
  doc/source/install/install-windows.rst
  doc/source/workflow.rst
  package.json
  requirements.txt
  scripts/install_fonts.sh
  scripts/install_resources.sh
  scripts/install_zds.sh
  scripts/texlive.profile
  setup.py
  yarn.lock
  zds/__init__.py
  zds/settings/abstract_base/zds.py
Labels: C-DevelopmentEnv, C-Docs, Feedback, S-Évolution
