Repository zestedesavoir/zds-site, pull requests merged in 2018-08, with the labels that each got.

#4928 Ne renvoit plus d'erreur 500 si le .git est absent
  zds/utils/context_processor.py
Labels: C-Back

#4940 Corrige l'obtention du slug d'un tag avant sa recherche dans la bibliothèque
  zds/tutorialv2/views/published.py
Labels: C-Back, S-BUG

#4955 Clarifie et homogénéise la page des paramètres du compte (fixes #4946)
  templates/member/settings/base.html
  templates/member/settings/profile.html
  templates/member/settings/unregister.html
Labels: C-Front

#4951 Ajout du smiley " :B "
  assets/js/editor.js
  assets/smileys/b.png
  zds/utils/templatetags/smileys_def.py
Labels: C-Front

#4870 N'envoie pas de MP à l'auteur d'un billet dépublié quand c'est l'auteur lui-même qui le dépublie
  zds/tutorialv2/views/validations.py
Labels: C-Back, S-BUG

#4997 Mets à jour l'installation zmarkdown dev
  .travis.yml
  Makefile
  zmd/.gitignore
  zmd/package.json
  zmd/yarn.lock
Labels: S-Évolution

#5011 Fix #4862 : s'assure d'une redirection correcte lors de la connexion
  zds/member/views.py
Labels: C-Back, Facile

#4994 [Reprise] Améliore l'interface de modération des billets
  assets/js/tribune-pick.js
  templates/header.html
  templates/tutorialv2/messages/validation_unpublish_opinion.md
  templates/tutorialv2/validation/opinions.html
  templates/tutorialv2/view/content.html
  templates/tutorialv2/view/content_online.html
  zds/tutorialv2/forms.py
  zds/tutorialv2/views/validations.py
  zds/utils/templatetags/interventions.py
Labels: C-Back, C-Front, S-Évolution

#5018 Affiche la description du groupe sur les détails d'une casquette
  templates/member/hat.html
  zds/member/tests/tests_views.py
  zds/member/views.py
Labels: C-Front, S-Évolution

#5023 Fix #5022: les messages masqués ne sont plus considérés comme utiles
  templates/misc/message.part.html
  zds/forum/tests/tests_views.py
Labels: C-Front, S-BUG

#5036 Retire le message de contenu modéré sur les tutoriels et articles
  templates/tutorialv2/view/content.html
Labels: C-Front, S-BUG
