Repository zestedesavoir/zds-site, pull requests merged in 2019-09, with the labels that each got.

#5428 [v28.2]Fait en sorte que le bouton d'export réagisse
  assets/js/content-export.js
  templates/tutorialv2/view/content_online.html
Labels: C-Front

#5430 [28.2] Remplace "tutoriaux" par "tutoriels" (fix #5423)
  templates/member/profile.html
Labels: S-BUG

#5432 [28.2] N'affiche pas d'erreur dans la console en dehors de la page de profil
  assets/js/userprofile-bio.js
Labels: C-Front, S-BUG

#5450 [hotfix] L'absence de sous-titre n'est plus remplacée par None
  templates/tutorialv2/view/content_online.html
  zds/tutorialv2/models/database.py
Labels: Bloquant, C-Back, S-Régression

#5449 [hotfix] Corrige l'exportation du Markdown depuis l'API (fix #5448)
  zds/tutorialv2/api/views.py
Labels: Bloquant, C-Back, S-BUG
