Repository zestedesavoir/zds-site, pull requests merged in 2019-11, with the labels that each got.

#5027 Fait en sorte que le suivi de la validation & béta test soit sur 1 MP
  doc/source/back-end-code/utils.rst
  zds/notification/receivers.py
  zds/tutorialv2/migrations/0023_publishablecontent_validation_private_message.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/models/mixins.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/validations.py
  zds/utils/mps.py
Labels: C-Back, S-Évolution

#5492 Fix #5476 : Correction comportement bannière cookie
  templates/base.html
Labels: C-Front, S-BUG

#5440 Amélioration du script d'installation
  scripts/dependencies/arch.txt
  scripts/dependencies/debian.txt
  scripts/dependencies/fedora.txt
  scripts/dependencies/ubuntu.txt
  scripts/install_zds.sh
Labels: C-DevelopmentEnv

#5514 Profil: enlève le gras de la barre de recherche (fix #5509)
  assets/scss/pages/_flexpage.scss
Labels: C-Front, S-BUG

#5485 Gestion des contributions aux contenus de ZdS
  assets/scss/components/_modals.scss
  fixtures/content_contribution_role.yaml
  templates/member/profile.html
  templates/tutorialv2/contributions.html
  templates/tutorialv2/includes/tags_authors.part.html
  templates/tutorialv2/messages/add_contribution_pm.md
  templates/tutorialv2/view/content.html
  zds/member/views.py
  zds/tutorialv2/admin.py
  zds/tutorialv2/forms.py
  zds/tutorialv2/migrations/0028_auto_20191024_1918.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/urls/urls_articles.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/urls/urls_opinions.py
  zds/tutorialv2/urls/urls_tutorials.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/published.py
Labels: C-Back

#5520 Corrige l'erreur 404 sur l'ajout d'une section
  templates/tutorialv2/includes/child.part.html
Labels: C-Front, S-BUG

#5523 Précise le paramètre dns pour la configuration de développement
  zds/settings/dev.py
Labels: C-DevelopmentEnv, S-BUG

#5189 Améliore l'historique d'édition sur le forum
  doc/source/front-end/template-tags.rst
  templates/pages/comment_edits_history.html
  zds/utils/templatetags/sibling.py
Labels: C-Front, S-Évolution

#5524 fix #5489 : rend utilisable l'ajout d'un auteur sur la page beta
  templates/tutorialv2/includes/tags_authors.part.html
Labels: C-Front, S-Évolution
