Repository zestedesavoir/zds-site, pull requests merged in 2019-10, with the labels that each got.

#5470 Enlève des caractères en trop dans le front (fix #5459)
  templates/tutorialv2/view/container.html
Labels: C-Front, S-BUG

#5451 Supprime CommonLayoutModalText
  zds/tutorialv2/forms.py
  zds/utils/forms.py
Labels: C-Back

#5483 Affiche l'éditeur dès que le DOM est chargé
  assets/js/editor.js
Labels: C-Front

#5487 Met à jour Pillow pour corriger la faille CVE-2019-16865
  requirements.txt
Labels: C-Back, S-BUG

#5488 Corrige la vue ExportView de l'API
  zds/tutorialv2/api/urls.py
  zds/tutorialv2/api/views.py
Labels: C-API, S-BUG
