Repository zestedesavoir/zds-site, pull requests merged in 2019-01, with the labels that each got.

#5136 La légende n'est plus ignorée lors de l'upload d'une image (fix #5118)
  zds/gallery/views.py
Labels: C-Front, S-BUG

#5220 Remet le bouton "télécharger l'archive" sur la version brouillon
  templates/tutorialv2/base.html
Labels: Bloquant, C-Front, S-Régression

#5227 Corrige la commande d'installation de zmarkdown dans la documentation
  doc/source/install/install-linux.rst
Labels: C-Docs

#5204 Met à jour le workflow
  doc/source/workflow.rst
Labels: C-Docs
