Repository zestedesavoir/zds-site, pull requests merged in 2019-06, with the labels that each got.

#5353 Utiliser Mathjax que là où on en a besoin
  templates/mathjax.html
  templates/mathjax_config.html
Labels: C-Front, S-BUG

#5357 Retire les abonnements aux sujets des forums privés quand on quitte un groupe
  zds/notification/receivers.py
Labels: C-Back, S-BUG

#5347 montre bouton version brouillon juste aux auteurs
  templates/tutorialv2/view/container.html
  templates/tutorialv2/view/content.html
Labels: C-Front, S-BUG

#5354 retire les espaces en trop dans les titres
  doc/source/front-end/template-tags.rst
  templates/base.html
  zds/utils/templatetags/trail.py
Labels: C-Front, S-BUG

#5302 Ajout d'un bouton pour supprimer une image dans la page d'édition
  templates/gallery/image/edit.html
Labels: C-Front
