Repository zestedesavoir/zds-site, pull requests merged in 2019-05, with the labels that each got.

#5211 Révision de la procédure d'installation windows
  doc/source/install/install-windows.rst
Labels: C-Docs

#5333 Ne lance pas les tests backend si seulement le frontend a été modifié
  scripts/travis_header.sh
  scripts/travis_run.sh
Labels: C-DevelopmentEnv

#5329 Le texte ne persiste plus après la validation (fix #5324)
  assets/js/editor-persistence.js
Labels: Bloquant, C-Front, S-BUG

#5318 Corrige l'affichage du dropdown pour les messages privés (fix #5317)
  assets/scss/components/_header-dropdown.scss
Labels: C-Front, S-Régression

#5331 Remet en orange les forums réservés à certains membres (fix #5330)
  assets/scss/components/_header-dropdown.scss
Labels: C-Front, S-Régression

#5321 On utilise la même version KaTeX que zmarkdown
  Gulpfile.js
  package.json
  yarn.lock
Labels: C-Front

#5344 ajout de l'insertion des smiley
  assets/js/editor.js
Labels: C-Front, S-Évolution

#5345 bug messages tronqués
  templates/forum/find/post.html
Labels: C-Front, S-BUG

#5250 Correction erreur 500 "Ajouter en Une"
  zds/featured/views.py
Labels: C-Back, S-BUG
