Repository zestedesavoir/zds-site, pull requests merged in 2019-08, with the labels that each got.

#4996 Facilite les propositions de unes
  Gulpfile.js
  assets/js/ajax-actions.js
  assets/js/featured-request-ignore.js
  assets/scss/layout/_sidebar.scss
  templates/featured/base.html
  templates/featured/includes/featured_request.part.html
  templates/featured/includes/featured_request_count.part.html
  templates/featured/list_requests.html
  templates/forum/topic/index.html
  templates/tutorialv2/view/content_online.html
  zds/featured/forms.py
  zds/featured/managers.py
  zds/featured/migrations/0007_featuredrequested.py
  zds/featured/mixins.py
  zds/featured/models.py
  zds/featured/tests.py
  zds/featured/urls.py
  zds/featured/views.py
  zds/forum/views.py
  zds/settings/abstract_base/zds.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/published.py
Labels: C-Back, C-Front, S-Évolution

#5408 Met à jour Django
  requirements.txt
Labels: C-Back

#5411 Ajoute une commande pour publier un contenu
  zds/tutorialv2/management/commands/validate_content.py
  zds/tutorialv2/publication_utils.py
  zds/tutorialv2/views/validations.py
  zds/utils/forums.py
Labels: Bloquant, C-Back

#5415 Met à jour la version du JDK
  scripts/define_variable.sh
  scripts/install_zds.sh
Labels: C-Back, S-BUG
