Repository zestedesavoir/zds-site, pull requests merged in 2020-10, with the labels that each got.

#5941 Amélioration du bandeau d'information
  assets/js/very-top-banner.js
  assets/scss/components/_very-top-banner.scss
  templates/base.html
  templates/top_banner.html
  templates/very_top_banner.html
  zds/settings/dev.py
Labels: C-Front, S-Évolution

#5946 Ne pas afficher `msg-are-hidden` pour 1er message
  templates/misc/message.part.html
Labels: C-Front, S-Évolution

#5947 Fixe espacement `msg-are-hidden`
  assets/scss/components/_topic-message.scss
Labels: C-Front, S-BUG

#5943 [29.3] Les menus de notification & utilisateur étaient trop haut sur tablette
  assets/scss/layout/_header.scss
Labels: C-Front, S-BUG, S-Régression

#5950 Ajout règle eslint indentation
  .editorconfig
Labels: C-DevelopmentEnv

#5954 Met à jour Sphinx et corrige les avertissements
  doc/source/back-end-code/tutorialv2.rst
  doc/source/front-end/elements-specifiques-au-site.rst
  doc/source/front-end/interface-utilisateur.rst
  doc/source/front-end/structure-du-site.rst
  doc/source/front-end/template-tags.rst
  doc/source/install/install-linux.rst
  requirements-dev.txt
  zds/utils/forms.py
Labels: C-Docs

#5958 Ajoute le profil de Clem dans les fixtures
  fixtures/users.yaml
Labels: C-DevelopmentEnv

#5959 Distingue les sujets lus et non-lus sur la page des derniers sujets
  zds/forum/urls.py
  zds/forum/views.py
Labels: C-Front, S-BUG

#5972 Personalise le message d'envoi d'image trop lourde
  assets/js/editor-new.js
Labels: S-BUG
