Repository zestedesavoir/zds-site, pull requests merged in 2020-06, with the labels that each got.

#5794 Fixe la version de zmarkdown pour pouvoir utiliser ce fichier en production
  zmd/package.json
Labels: C-Infra

#5817 Mise à jour de sécurité de Django
  requirements.txt
Labels: C-Back

#5827 Amélioration de l'intégration du lien de modification de la licence d'un contenu
  assets/scss/components/_modals.scss
  assets/scss/main.scss
  assets/scss/pages/_content-editor.scss
  assets/scss/variables/_colors.scss
  doc/source/front-end/interface-utilisateur.rst
  templates/tutorialv2/view/content.html
Labels: C-Front

#5824 Corrige le problème de sauvegarde avec plusieurs onglets ouverts + l'actualisation du pied de page
  assets/js/editor-new.js
  package.json
  yarn.lock
Labels: C-EasyMDE, C-Front

#5742 Retire les aides du formulaire de création/édition de contenu
  assets/js/content-helps.js
  assets/scss/base/_forms.scss
  assets/scss/layout/_sidebar.scss
  templates/tutorialv2/view/container.html
  templates/tutorialv2/view/content.html
  yarn.lock
  zds/tutorialv2/forms.py
  zds/tutorialv2/mixins.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/contents.py
Labels: C-Front
