Repository zestedesavoir/zds-site, pull requests merged in 2020-07, with the labels that each got.

#5832 Gestion des exports d'un contenu
  assets/js/content-export.js
  assets/scss/base/_forms.scss
  assets/scss/components/_modals.scss
  assets/scss/main.scss
  assets/scss/pages/_content-exports.scss
  templates/tutorialv2/includes/exports.part.html
  templates/tutorialv2/view/content.html
  templates/tutorialv2/view/content_online.html
  zds/tutorialv2/api/serializers.py
  zds/tutorialv2/api/tests.py
  zds/tutorialv2/api/urls.py
  zds/tutorialv2/api/views.py
  zds/tutorialv2/models/database.py
Labels: C-API, C-Front

#5847 Inclusivité de l'interface de rédaction de message
  templates/misc/message_form.html
  zds/forum/tests/tests.py
Labels: C-Front

#5856 Empêche de poster des alertes en apparence vides
  zds/forum/commons.py
  zds/tutorialv2/views/published.py
Labels: S-BUG

#5857 Utilise la même police pour les boutons sous les billets
  templates/tutorialv2/includes/alert.html
Labels: C-Front, S-BUG

#5854 Met à jour typographie et liens des astuces Markdown
  assets/js/markdown-help.js
Labels: C-Front

#5855 Correction de la documentation de l'installation sous Windows.
  doc/source/install/install-windows.rst
Labels: C-Docs

#5863 Corrige l'affichage de l'élément sous le champ de recherche sous Safari.
  assets/scss/pages/_flexpage.scss
Labels: C-Front, S-BUG

#5864 Corrige l'affichage du bouton du petit champ de recherche sur WebKit
  assets/scss/layout/_header.scss
Labels: C-Front, S-BUG

#5865 Permet de sauvegarder sans quitter
  assets/js/editor-button-save.js
  assets/js/editor-new.js
  zds/tutorialv2/factories.py
  zds/tutorialv2/forms.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/views/contents.py
  zds/utils/forms.py
Labels: C-Back, C-Front, S-Évolution

#5867 Mise à jour des dépendances Python
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
  scripts/generate_release_summary.py
  zds/forum/tests/tests.py
  zds/member/tests/tests_views.py
  zds/utils/management/commands/load_fixtures.py
Labels: C-Back

#5823 SCSS : mixins pour les media-queries adaptatives
  assets/scss/base/_base.scss
  assets/scss/base/_forms.scss
  assets/scss/base/_helpers.scss
  assets/scss/base/_high-pixel-ratio.scss
  assets/scss/components/_alert-box.scss
  assets/scss/components/_breadcrumb.scss
  assets/scss/components/_content-item.scss
  assets/scss/components/_featured-item.scss
  assets/scss/components/_header-dropdown.scss
  assets/scss/components/_header-search.scss
  assets/scss/components/_linkbox.scss
  assets/scss/components/_mobile-menu.scss
  assets/scss/components/_modals.scss
  assets/scss/components/_more-link.scss
  assets/scss/components/_notification-list.scss
  assets/scss/components/_pagination.scss
  assets/scss/components/_search-box.scss
  assets/scss/components/_topic-list.scss
  assets/scss/components/_topic-message.scss
  assets/scss/components/_user-profile.scss
  assets/scss/layout/_content.scss
  assets/scss/layout/_footer.scss
  assets/scss/layout/_header.scss
  assets/scss/layout/_main.scss
  assets/scss/pages/_flexpage.scss
  assets/scss/pages/_gallery.scss
  assets/scss/pages/_home.scss
  assets/scss/pages/_search.scss
  assets/scss/variables/_media-queries.scss
  doc/source/front-end/helpers-scss.rst
Labels: C-Docs, C-Front, Feedback, S-Refactorisation

#5868 Mise à jour des dépendances Node JS
  package.json
  yarn.lock
Labels: C-Front

#5869 [29.2] “Undefined” sur le bouton de demande d'export
  templates/tutorialv2/includes/exports.part.html
Labels: C-Front, S-BUG

#5870 Documentation : comment mettre à jour une PR par rapport à dev
  doc/source/contributing.rst
Labels: C-Docs

#5875 🚸 Suppression de la partie « Mon profil » de la barre latérale
  templates/header.html
Labels: C-Front, S-Refactorisation

#5859 🚸 Pluriel du message de prise en charge de contenu en validation
  templates/tutorialv2/messages/validation_reserve.md
Labels: C-Front, Feedback

#5877 [29.2] Il n'était pas possible d'annuler la validation
  zds/tutorialv2/views/validations.py
Labels: S-BUG, S-Régression

#5879 [29.2] L'API des demandes d'aide ne fonctionne pas en prod/bêta.
  zds/tutorialv2/urls/urls_contents.py
Labels: S-BUG, S-Régression

#5874 Ajout de Discord et de GitHub au pied de page
  assets/images/sprite/discord-blue.png
  assets/images/sprite/discord-blue@2x.png
  assets/images/sprite/discord-light.png
  assets/images/sprite/discord-light@2x.png
  assets/images/sprite/discord.png
  assets/images/sprite/discord@2x.png
  assets/scss/base/_icons.scss
  templates/footer.html
  zds/settings/abstract_base/zds.py
Labels: C-Front

#5880 [29.2] Les pinaillages de l'interface d'exports.
  assets/js/content-export.js
  assets/scss/pages/_content-exports.scss
  templates/tutorialv2/includes/exports.part.html
Labels: C-Front, S-BUG

#5887 🐛 Changement de classe de l'encadré « Signalement du profil »
  templates/member/profile.html
Labels: C-Front, S-BUG

#5882 💄 Cohérence du fond des menu déroulants d'EasyMDE
  assets/scss/components/_editor-new.scss
Labels: C-Front, S-BUG

#5883 Templatetag remplacant une espace par une espace insécable
  templates/featured/includes/featured_resource_item.part.html
  zds/utils/templatetags/french_typography.py
  zds/utils/tests/tests_french_typography.py
Labels: C-Front

#5891 [v29.2] Corrige l'affichage des demandes d'aide
  templates/tutorialv2/view/container.html
  templates/tutorialv2/view/content.html
  zds/tutorialv2/mixins.py
  zds/tutorialv2/views/contents.py
Labels: C-Front

#5892 Supprime les messages privés de l'administration de Django
  zds/mp/admin.py
Labels: S-Évolution

#5885 Refactorise et améliore le CSS de l'en-tête du site
  assets/scss/layout/_header.scss
  templates/header.html
Labels: C-Front, S-Refactorisation

#5895 Correction d'une erreur de classe à l'origine du non-affichage de certains menus
  templates/member/base.html
Labels: C-Front, S-BUG, S-Régression

#5897 Corrige l'affichage de la page de profil et réorganise les templates d'administration
  templates/member/admin/add_banned_email_provider.html
  templates/member/admin/banned_email_providers.html
  templates/member/admin/base.html
  templates/member/admin/hat_request.html
  templates/member/admin/memberip.html
  templates/member/admin/members_with_provider.html
  templates/member/admin/new_email_providers.html
  templates/member/admin/promote.html
  templates/member/admin/requested_hats.html
  templates/member/admin/solved_hat_requests.html
  templates/member/base.html
  zds/member/views.py
Labels: C-Front, S-BUG, S-Refactorisation, S-Régression
