Repository zestedesavoir/zds-site, pull requests merged in 2020-11, with the labels that each got.

#5975 Adapte le type d'une note de karma (pour eviter les erreur 500)
  zds/member/migrations/0020_auto_20201018_0841.py
  zds/member/models.py
Labels: S-BUG

#5973 Correction du retour de plein écran
  assets/scss/base/_base.scss
Labels: C-EasyMDE, S-BUG

#5974 Afficher la liste des commentaires d'un membre
  templates/member/profile.html
  templates/tutorialv2/comment/list.html
  zds/member/views.py
  zds/tutorialv2/managers.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/lists.py
Labels: S-Évolution

#5986 Répare le bouton « Sauvegarder et continuer »
  assets/js/editor-button-save.js
  assets/js/editor-new.js
Labels: Bloquant, S-BUG

#5988 Corrige le mode compatibilité
  assets/js/editor-new.js
Labels: C-Front
