Repository zestedesavoir/zds-site, pull requests merged in 2020-09, with the labels that each got.

#5900 Harmonise les licences des fixtures avec celles de la prod
  Makefile
  doc/source/utils/fixture_loaders.rst
  fixtures/licences.yaml
  zds/utils/management/commands/load_fixtures.py
Labels: C-DevelopmentEnv

#5921 Retire du code inutile de la gestion des tags
  zds/tutorialv2/forms.py
  zds/tutorialv2/tests/tests_views/tests_editcontenttags.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/display.py
  zds/tutorialv2/views/editorialization.py
Labels: Bloquant, C-Back, S-Refactorisation

#5925 [29.3] Correction de l'affichage des casquettes du profil
  assets/scss/components/_user-profile.scss
  templates/member/profile.html
  zds/member/models.py
Labels: C-Front, S-BUG
