Repository zestedesavoir/zds-site, pull requests merged in 2020-12, with the labels that each got.

#6002 Permet de faire tomber des cœurs pour la Saint-Valentin
  assets/js/snow.js
  doc/source/front-end/elements-specifiques-au-site.rst
Labels: C-Front, S-Évolution

#5944 L'installeur en version complète ne persiste plus définitivement le PATH du moment de l'installation du JDK
  scripts/install_zds.sh
Labels: C-DevelopmentEnv, S-BUG

#5976 Découple le module de forum du module de notification
  zds/forum/commons.py
  zds/forum/models.py
  zds/forum/signals.py
  zds/forum/tests/tests_views.py
  zds/forum/views.py
  zds/notification/receivers.py
Labels: C-Back

#5982 Découple le module de notification et le module de tuto
  zds/notification/receivers.py
  zds/notification/tests/tests_basics.py
  zds/notification/tests/tests_tricky.py
  zds/tutorialv2/publication_utils.py
  zds/tutorialv2/signals.py
  zds/tutorialv2/utils.py
  zds/tutorialv2/views/display.py
Labels: C-Back

#5945 Fermeture de la bannière synchronisée sur tous les onglets si définitif
  assets/js/very-top-banner.js
Labels: C-Front, S-Évolution
