Repository zestedesavoir/zds-site, pull requests merged in 2020-01, with the labels that each got.

#5557 Fix le "None" qui apparaît quand il n'y a pas d'intro/ccl
  zds/tutorialv2/models/versioned.py
Labels: C-Front, Facile, S-BUG

#5562 Ajoute une dépendance implicite et obligatoire de social-auth-app-django
  requirements.txt
Labels: C-Back, S-BUG

#5578 update pillow (security + perfs + reliability)
  requirements.txt
Labels: C-Back, C-Infra

#5574 Mise à jour de EasyMDE
  package.json
  yarn.lock
Labels: C-Front

#5576 (EasyMDE) Les requêtes de prévisualisation ne bloque plus la zone d'écriture
  assets/js/editor.js
Labels: C-Front, S-BUG

#5583 Corrige le titre des Unes
  assets/scss/components/_featured-item.scss
Labels: C-Front, S-Régression

#5591 (EasyMDE) Corrige la citation des messages
  assets/js/ajax-actions.js
  assets/js/editor.js
Labels: C-Front, S-BUG

#5596 (EasyMDE) Corrige l'envoi des formulaires avec l'attribut "required"
  assets/js/editor.js
Labels: Bloquant, C-Front, S-Régression

#5597 (EasyMDE) Correction temporaire de la sauvegarde automatique
  assets/js/editor.js
Labels: C-Front, S-BUG

#5588 Il n'est plus nécessaire d'avoir un tag avec le front déjà généré
  .travis.yml
  scripts/push_front.sh
Labels: C-Infra

#5601 fix #5599 les urls des suggestions sont publiques
  templates/tutorialv2/includes/content_suggestion.part.html
Labels: Bloquant, C-Front

#5606 Retire les balises HTML visibles sur la page de profil lorsqu'un membre a des abonnés
  templates/member/profile.html
Labels: C-Front, S-BUG

#5610 Accessibilité et performance: follow up des conseils dareboost
  assets/js/userprofile-bio.js
  assets/scss/layout/_main.scss
  templates/member/profile.html
  templates/searchv2/includes/publishedcontent.part.html
  templates/tutorialv2/includes/content_item.part.html
  templates/tutorialv2/view/base_categories.html
  zds/searchv2/forms.py
Labels: C-Front

#5586 Utilise rel="nofollow" sur les signatures
  zds/utils/templatetags/emarkdown.py
  zds/utils/tests/tests_emarkdown.py
Labels: C-Front

#5577 Change le style des signatures pour ne plus décaler les boutons
  assets/scss/components/_topic-message.scss
  assets/scss/components/_user-profile.scss
Labels: C-Front, S-BUG

#5585 Corrige l'affichage des erreurs syntaxes lancées par gulp
  Gulpfile.js
Labels: C-DevelopmentEnv

#5622 Corrige la formulation d'une phrase
  templates/tutorialv2/includes/tags_authors.part.html
Labels: C-Front
