Repository zestedesavoir/zds-site, pull requests merged in 2020-04, with the labels that each got.

#5621 Passage à NodeJS 12 LTS
  .nvmrc
Labels: C-Front, S-Évolution

#5691 Ajoute les navigateurs supportés dans la documentation
  doc/source/front-end.rst
Labels: C-Docs

#5643 Correction : un staff/admin peut désormais s'ajouter lui-même comme auteur
  zds/tutorialv2/views/contents.py
Labels: C-Back

#5705 Affiche la bonne date de dernière modification
  templates/tutorialv2/includes/tags_authors.part.html
  zds/tutorialv2/models/database.py
Labels: Bloquant, C-Back, S-BUG

#5697 Un seul fichier comme README et page de garde de la doc
  README.md
  README.rst
  doc/source/index.rst
Labels: C-Docs, Feedback

#5713 Ajoute un bandeau pour distinguer les versions locale, bêta et prod
  assets/scss/base/_base.scss
  assets/scss/components/_very-top-banner.scss
  assets/scss/main.scss
  templates/base.html
  zds/settings/abstract_base/zds.py
  zds/settings/beta.py
  zds/settings/dev.py
  zds/settings/prod.py
Labels: C-Front, Feedback

#5689 Ajout du système de regroupement des lignes sensibles dans travis
  .travis.yml
  scripts/travis_overview/grep_ignore_msg.txt
  scripts/travis_overview/sed_parsing_rules.txt
  scripts/travis_overview/travis_overview.sh
Labels: C-DevelopmentEnv, Feedback

#5714 Corrige l'affichage de la neige avec le bandeau des cookies
  assets/js/snow.js
Labels: C-Front, S-BUG

#5737 Corrige le script d'installation pour lancer nvm
  scripts/install_zds.sh
Labels: C-DevelopmentEnv, S-Régression

#5629 Amélioration de la journalisation pour la production
  zds/settings/prod.py
Labels: C-Infra, S-Évolution
