Repository zestedesavoir/zds-site, pull requests merged in 2021-02, with the labels that each got.

#5612 [WIP]fix #5079 fini g+
  assets/images/brands/facebook.svg
  assets/images/brands/google.svg
  assets/images/sprite/foursquare-blue.png
  assets/images/sprite/foursquare-blue@2x.png
  assets/images/sprite/foursquare-light.png
  assets/images/sprite/foursquare-light@2x.png
  assets/images/sprite/foursquare.png
  assets/images/sprite/foursquare@2x.png
  assets/images/sprite/google-plus-blue.png
  assets/images/sprite/google-plus-blue@2x.png
  assets/images/sprite/google-plus-light.png
  assets/images/sprite/google-plus-light@2x.png
  assets/images/sprite/google-plus.png
  assets/images/sprite/google-plus@2x.png
  assets/scss/base/_forms.scss
  assets/scss/base/_icons.scss
  assets/scss/variables/_colors.scss
  base.db.spam
  templates/member/includes/login_button.part.html
  templates/member/login.html
  templates/member/register/index.html
Labels: Bloquant, C-Front, Facile, Feedback

#6016 Le drapeau de spam potentiel est disponible partout
  assets/js/ajax-actions.js
  assets/js/potential-spam.js
  templates/forum/topic/index.html
  templates/misc/message.part.html
  zds/api/urls.py
  zds/forum/commons.py
  zds/forum/migrations/0020_rename_post_is_potential_spam_to_temp_name_for_migration.py
  zds/forum/migrations/0021_remove_post_is_potential_spam.py
  zds/forum/models.py
  zds/forum/tests/tests_views.py
  zds/forum/urls.py
  zds/forum/views.py
  zds/utils/api/permissions.py
  zds/utils/api/serializers.py
  zds/utils/api/tests.py
  zds/utils/api/urls.py
  zds/utils/api/views.py
  zds/utils/migrations/0023_move_potential_spam_to_comment_model.py
  zds/utils/models.py
  zds/utils/tests/tests_comments.py
Labels: C-API, C-Back, S-Évolution

#6028 Corrige l'affichage des alertes sur les billets (#6011)
  zds/utils/header_notifications.py
Labels: C-Back

#6031 On peut se déconnecter depuis un mobile
  assets/scss/layout/_header.scss
Labels: Bloquant, C-Front, S-Régression

#6035 Les boutons ne s'empilent plus sur les titres des parties d'un contenu
  assets/scss/base/_content.scss
Labels: C-Front, S-BUG

#6037 N'affiche que les trois points du menu des message sur mobile
  assets/scss/components/_topic-message.scss
Labels: C-Front, S-Évolution

#6020 Adieu node-sass et node-gyp, bienvenue dart-sass !
  Gulpfile.js
  assets/scss/base/_base.scss
  assets/scss/layout/_header.scss
  package.json
  yarn.lock
Labels: C-DevelopmentEnv, C-Front

#6010 Thème de coloration syntaxique accessible et aux couleurs de ZdS
  Gulpfile.js
  assets/js/editor-new.js
  assets/scss/base/_source-code.scss
  assets/scss/highlight/_zest-codemirror.scss
  assets/scss/highlight/_zest-hljs.scss
  assets/scss/main.scss
  assets/scss/zmd.scss
  package.json
  templates/base.html
  yarn.lock
Labels: C-Front, Feedback

#5471 Ne souligne pas le texte d'un bouton lors du hover (fix #5366)
  assets/scss/layout/_content.scss
Labels: C-Front, S-BUG

#6044 [v30]: fix le bug de l'antispam qui empêchait les spoilers d'être int…
  assets/js/potential-spam.js
Labels: Bloquant, C-Front, S-Régression

#6049 Ajoute une commande pour vider le cache
  zds/utils/management/commands/clear_cache.py
Labels: Bloquant
