Repository zestedesavoir/zds-site, pull requests merged in 2021-10, with the labels that each got.

#6180 Cache les boutons éditer et citer pour les messages des MPs avec une seule personne
  templates/mp/topic/index.html
Labels: hacktoberfest-accepted

#6171 Remplace django-rest-swagger par drf-yasg
  assets/scss/pages/_api.scss
  requirements.txt
  templates/drf-yasg/swagger-ui.html
  templates/rest_framework_swagger/index.html
  zds/api/urls.py
  zds/mp/api/views.py
  zds/settings/abstract_base/django.py
  zds/tutorialv2/api/views.py
  zds/tutorialv2/urls/urls_tutorials.py
Labels: C-Docs, C-API

#6183 S'assure que l'OS choisi pour installation est un nombre
  scripts/install_zds.sh
Labels: hacktoberfest-accepted

#6167 Ajoute un guide dans la doc sur l'écriture de tests back
  doc/source/guides.rst
  doc/source/guides/backend-tests.rst
  doc/source/guides/write-backend-tests.rst
Labels: C-Docs

#6187 Met a jour le canal discord dans l'encart Contactez-nous de la doc
  doc/source/includes/contact-us.rst
Labels: C-Docs, hacktoberfest-accepted

#6202 Corrige deux tests mal nommés et donc non découverts
  zds/tutorialv2/tests/tests_views/tests_content.py
Labels: C-Back

#6201 Retire le champ de recherche (inactif) sur les profils
  templates/member/profile.html
Labels: C-Front, hacktoberfest-accepted

#6200 Ajoute des variantes italiques pour Merriweather
  templates/base.html
Labels: C-Front, hacktoberfest-accepted
