Repository zestedesavoir/zds-site, pull requests merged in 2021-09, with the labels that each got.

#6157 Correctifs de sécurité
  zds/tutorialv2/publication_utils.py
  zds/utils/templatetags/emarkdown.py
  zmd/package.json
Labels: S-BUG, Bloquant

#6133 Corrige une marge sur une liste de tutos/articles de la bibliothèque
  assets/scss/components/_pagination.scss
  assets/scss/pages/_flexpage.scss
Labels: C-Front

#6156 Compte les commentaires non masqués
  zds/tutorialv2/managers.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/views/lists.py
Labels: C-Back

#6148 Vérifie que le champ CSRF existe avant de récupérer sa valeur
  assets/js/common/ajax.js
Labels: S-BUG, C-Front, Bloquant

#6149 Réduit la verbosité des logs de l'environnement de dev
  zds/settings/dev.py
Labels: C-DevelopmentEnv

#6162 Mise à jour de Sphinx et sphinx_rtd_theme
  doc/Makefile
  doc/make.bat
  doc/source/conf.py
  requirements-dev.txt
Labels: C-Docs

#6174 Corrige des logs en double sur l'environnement de dév (#6159)
  zds/settings/dev.py
Labels: C-Back, C-DevelopmentEnv

#6172 Change les TRUE en 1 dans les requêtes SQL en dur
  zds/tutorialv2/managers.py
  zds/tutorialv2/views/lists.py
Labels: C-Back, C-DevelopmentEnv

#6165 Ajoute un pense-bête pour les tests back au template de PR
  .github/pull_request_template.md
Labels: S-Évolution, C-DevelopmentEnv

#6166 Ajoute un guide sur les tests backend
  doc/source/guides.rst
  doc/source/guides/backend-tests.rst
Labels: C-Docs
