Repository zestedesavoir/zds-site, pull requests merged in 2021-03, with the labels that each got.

#6059 (v30) Petites corrections dans les actions des messages
  templates/misc/message.part.html
Labels: Bloquant

#6064 Passage à zmarkdown 9.1.4 pour corriger un bug
  zmd/package.json
Labels: Bloquant

#6045 Les fixtures ne référencent plus les permissions par PK
  fixtures/users.yaml
Labels: C-DevelopmentEnv, S-BUG, S-Refactorisation

#6067 Permet l'utilisation de svg dans la gallerie
  requirements.txt
  zds/gallery/api/tests.py
  zds/gallery/forms.py
  zds/gallery/mixins.py
  zds/gallery/views.py
  zds/settings/abstract_base/requirements.py
  zds/tutorialv2/forms.py
  zds/tutorialv2/views/contents.py
  zds/utils/validators.py
Labels: C-Back, S-Évolution
