Repository zestedesavoir/zds-site, pull requests merged in 2021-04, with the labels that each got.

#6083 Ajoute un filtre sur l'état de lecture des notifications dans l'API
  zds/notification/api/tests.py
  zds/notification/api/views.py
Labels: C-API

#6089 Réduit la quantité de requêtes réalisées sur la page d'accueil des forums
  doc/source/front-end/template-tags.rst
  templates/forum/base.html
  templates/forum/includes/forums.part.html
  zds/forum/managers.py
  zds/forum/models.py
  zds/forum/tests/tests.py
  zds/forum/views.py
  zds/notification/tests/tests_basics.py
  zds/utils/management/commands/load_fixtures.py
  zds/utils/templatetags/interventions.py
Labels: C-Back, S-Évolution

#6025 Change la manière de faire la publication des tuto et des latex
  templates/tutorialv2/export/chapter.html
  templates/tutorialv2/includes/exports.part.html
  yarn.lock
  zds/tutorialv2/api/views.py
  zds/tutorialv2/factories.py
  zds/tutorialv2/publication_utils.py
  zds/tutorialv2/publish_container.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/utils.py
  zds/utils/templatetags/emarkdown.py
  zds/utils/tests/tests_emarkdown.py
  zmd/package.json
Labels: C-Back, S-Refactorisation
