Repository zestedesavoir/zds-site, pull requests merged in 2021-11, with the labels that each got.

#6206 Mise à jour des dépendances Python
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
Labels: C-Back

#6208 Améliore les messages d'erreur pour l'importation d'image
  zds/gallery/views.py
Labels: C-Back

#6182 Utilise le KaTeX de zmd pour ZdS
  Gulpfile.js
  package.json
  scripts/install_zds.sh
  yarn.lock
Labels: hacktoberfest-accepted

#6210 Corrige le lien de progdupeupl
  zds/settings/abstract_base/zds.py
Labels: C-Front

#6214 Utilise les commandes make dans la documentation pour contribuer à ZdS
  doc/source/contributing.rst
Labels: C-Docs

#6181 Grise les boutons de comparaisons de versions si elles sont identiques
  templates/tutorialv2/view/content.html
  zds/tutorialv2/mixins.py
Labels: hacktoberfest-accepted
