Repository zestedesavoir/zds-site, pull requests merged in 2022-10, with the labels that each got.

#6388 Mise à jour des dépendances Node.js
  assets/js/editor-new.js
  package.json
  yarn.lock
Labels: C-Front

#6393 Supprime une fixture obsolète
  fixtures/advanced/articles.yaml
Labels: C-DevelopmentEnv, hacktoberfest-accepted

#6396 Refactorisation de la page de désinscription
  assets/scss/base/_content.scss
  templates/member/settings/unregister.html
Labels: C-Front

#6394 Corrige l'affichage des longs pseudos sur le profil sur mobile
  assets/scss/pages/_flexpage.scss
Labels: C-Front, hacktoberfest-accepted

#6395 Corrige le style du pied-de-page pour qu'il ne dépasse plus
  assets/scss/layout/_footer.scss
Labels: C-Front, hacktoberfest-accepted

#6398 Corrige la taille des images de profil par défaut
  templates/forum/base.html
  templates/header.html
  templates/member/profile.html
  templates/misc/member_item.part.html
  templates/misc/message_user.html
  zds/member/models.py
  zds/member/tests/tests_models.py
  zds/utils/templatetags/profile.py
Labels: C-Front, hacktoberfest-accepted

#6401 Améliore l'affichage de l'estimation du temps de lecture
  templates/tutorialv2/includes/tags_authors.part.html
  zds/utils/templatetags/humanize_duration.py
  zds/utils/templatetags/minute_to_duration.py
  zds/utils/tests/tests_humanize_duration.py
  zds/utils/tests/tests_minute_to_duration.py
Labels: C-Back, hacktoberfest-accepted

#6406 Corrige le domaine pour les placeholders des Unes
  fixtures/featured.yaml
Labels: C-DevelopmentEnv, hacktoberfest-accepted

#6405 Refactorise les URL de zds.member
  zds/member/urls.py
Labels: C-Back, hacktoberfest-accepted

#6404 Toilettage des vues des MP
  zds/mp/tests/tests_views.py
  zds/mp/views.py
Labels: C-Back, hacktoberfest-accepted
