Repository zestedesavoir/zds-site, pull requests merged in 2022-06, with the labels that each got.

#6327 Correction mineure dans la documentation
  doc/source/back-end/contents.rst
Labels: C-Docs

#6322 Corrige le texte de la modale d'exports des contenus
  templates/tutorialv2/includes/exports.part.html
Labels: C-Front

#6318 Corrige le contenu des ePUBs pour interpréter l'HTML
  zds/utils/templatetags/emarkdown.py
  zds/utils/tests/tests_emarkdown.py
Labels: S-BUG, C-Epub

#6332 Ajoute l'URL /api/ à ne pas indexer au fichier robots.txt
  robots.txt
Labels: C-Infra

#6336 Supprime les frais et le template de la page d'adhésion à l'association
  templates/pages/assoc_subscribe.html
  zds/settings/abstract_base/zds.py
Labels: S-Refactorisation

#6330 Autorise uniquement les requêtes POST pour signaler une faute dans un contenu
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/views/misc.py
Labels: S-BUG, C-Back

#6333 Gère les exceptions qui ne sont pas les nôtres pour les statistiques
  zds/tutorialv2/views/statistics.py
Labels: S-BUG, C-Back

#5940 Journal des événements sur un contenu
  templates/tutorialv2/events/descriptions.part.html
  templates/tutorialv2/events/list.html
  templates/tutorialv2/view/content.html
  zds/notification/__init__.py
  zds/notification/apps.py
  zds/notification/models.py
  zds/tutorialv2/admin.py
  zds/tutorialv2/migrations/0032_event.py
  zds/tutorialv2/models/events.py
  zds/tutorialv2/signals.py
  zds/tutorialv2/tests/models/__init__.py
  zds/tutorialv2/tests/models/tests_models.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_views/tests_addcontributor.py
  zds/tutorialv2/tests/tests_views/tests_addsuggestion.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_editcontenttags.py
  zds/tutorialv2/tests/tests_views/tests_events.py
  zds/tutorialv2/tests/tests_views/tests_removecontributor.py
  zds/tutorialv2/tests/tests_views/tests_removesuggestion.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/authors.py
  zds/tutorialv2/views/beta.py
  zds/tutorialv2/views/contributors.py
  zds/tutorialv2/views/editorialization.py
  zds/tutorialv2/views/events.py
  zds/tutorialv2/views/help.py
  zds/tutorialv2/views/validations_contents.py
  zds/tutorialv2/views/validations_opinions.py
Labels: C-Back

#6310 Vide le stockage local lors de l'envoi avec Ctrl+Entrée
  assets/js/editor-new.js
Labels: S-BUG, C-Front

#6340 Mise à jour triviale des dépendances Python
  requirements-ci.txt
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
  zds/member/tests/tests_front.py
  zds/tutorialv2/tests/__init__.py
  zds/tutorialv2/tests/tests_front.py
Labels: C-Back

#6341 Mise à jour triviale des dépendances Node.js
  .eslintrc.yaml
  package.json
  yarn.lock
Labels: C-Front

#6301 Déplace HelpWriting dans les tutos
  fixtures/advanced/aide_tuto_media.yaml
  zds/tutorialv2/admin.py
  zds/tutorialv2/forms.py
  zds/tutorialv2/migrations/0033_move_helpwriting.py
  zds/tutorialv2/mixins.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/models/help_requests.py
  zds/tutorialv2/tests/factories.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/views/help.py
  zds/utils/admin.py
  zds/utils/management/tests.py
  zds/utils/migrations/0025_move_helpwriting.py
  zds/utils/models.py
  zds/utils/tests/factories.py
Labels: C-Back, S-Refactorisation
