Repository zestedesavoir/zds-site, pull requests merged in 2022-07, with the labels that each got.

#6284 Refactorise les urls des Mise en une
  templates/featured/base.html
  templates/featured/index.html
  templates/featured/list_requests.html
  templates/featured/resource/update.html
  templates/forum/topic/index.html
  templates/header.html
  templates/home.html
  templates/tutorialv2/view/content_online.html
  zds/featured/forms.py
  zds/featured/tests/tests.py
  zds/featured/urls.py
  zds/featured/views.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6293 Refactorise les URL de la galerie
  templates/gallery/base.html
  templates/gallery/gallery/details.html
  templates/gallery/gallery/list.html
  templates/gallery/image/edit.html
  templates/header.html
  templates/tutorialv2/create/container.html
  templates/tutorialv2/create/extract.html
  templates/tutorialv2/edit/container.html
  templates/tutorialv2/edit/content.html
  templates/tutorialv2/edit/extract.html
  templates/tutorialv2/view/content.html
  zds/gallery/forms.py
  zds/gallery/models.py
  zds/gallery/tests/tests_models.py
  zds/gallery/tests/tests_views.py
  zds/gallery/urls.py
  zds/gallery/views.py
  zds/member/forms.py
  zds/member/tests/views/tests_login.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6296 Refactorise les URL munin
  zds/munin/urls.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6297 Refactorise les URL de notifications
  templates/header.html
  templates/notification/followed.html
  zds/notification/tests/tests_basics.py
  zds/notification/urls.py
  zds/notification/views.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6298 Refactorise les URL de 'pages'
  zds/pages/urls.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6299 Refactorise les URL de recherche
  zds/searchv2/urls.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6329 Supprime les caractères non supportés par les flux RSS et ATOM
  zds/forum/feeds.py
  zds/forum/tests/tests_feeds.py
  zds/tutorialv2/feeds.py
  zds/tutorialv2/tests/tests_feeds.py
  zds/utils/feeds.py
Labels: S-BUG, C-Back, S-Refactorisation

#5949 Force affichage message si cible ancre
  assets/scss/components/_topic-message.scss
Labels: C-Front, S-Évolution

#6350 Importer une nouvelle version d'un contenu ne mélange plus les introductions et conclusions
  zds/tutorialv2/models/versioned.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/views/archives.py
Labels: C-Back

#6288 Refactorise le module de MP
  templates/header.html
  templates/member/profile.html
  templates/member/sidebar.html
  templates/mp/base.html
  templates/mp/index.html
  templates/mp/post/edit.html
  templates/mp/post/new.html
  templates/mp/topic/index.html
  templates/tutorialv2/view/content.html
  zds/mp/commons.py
  zds/mp/forms.py
  zds/mp/models.py
  zds/mp/tests/tests_models.py
  zds/mp/tests/tests_utils.py
  zds/mp/tests/tests_views.py
  zds/mp/urls.py
  zds/mp/views.py
  zds/notification/tests/tests_basics.py
  zds/tutorialv2/forms.py
  zds/tutorialv2/models/database.py
  zds/urls.py
Labels: C-Back, S-Refactorisation

#6300 Refactorise les URL des contenus
  zds/tutorialv2/urls/__init__.py
  zds/tutorialv2/urls/urls_articles.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/urls/urls_opinions.py
  zds/tutorialv2/urls/urls_publications.py
  zds/tutorialv2/urls/urls_tutorials.py
  zds/tutorialv2/urls/urls_validations.py
Labels: C-Back, S-Refactorisation

#6295 Refactorise les URL du forum
  templates/base.html
  templates/forum/base.html
  templates/forum/category/forum.html
  templates/forum/find/post.html
  templates/forum/find/topic_by_tag.html
  templates/forum/includes/feed.part.html
  templates/forum/includes/topic_item.part.html
  templates/forum/includes/topic_row.part.html
  templates/forum/includes/topic_solve_form.part.html
  templates/forum/last_topics.html
  templates/forum/post/new.html
  templates/forum/topic/index.html
  templates/header.html
  templates/home.html
  templates/member/profile.html
  zds/featured/tests/tests.py
  zds/forum/forms.py
  zds/forum/models.py
  zds/forum/tests/tests.py
  zds/forum/tests/tests_feeds.py
  zds/forum/tests/tests_views.py
  zds/forum/urls.py
  zds/forum/views.py
  zds/member/views/profile.py
  zds/member/views/register.py
  zds/notification/tests/tests_basics.py
  zds/notification/tests/tests_tricky.py
  zds/pages/tests.py
  zds/searchv2/tests/tests_views.py
  zds/urls.py
  zds/utils/models.py
  zds/utils/tests/tests_comments.py
Labels: C-Back, S-Refactorisation

#6331 Gère les utilisateurs inexistants dans RedirectOldContentOfAuthor
  zds/tutorialv2/tests/tests_views/tests_redirect.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/redirect.py
Labels: S-BUG, C-Back

#6273 Remplace la vue de login par la LoginView de Django
  zds/member/forms.py
  zds/member/models.py
  zds/member/tests/tests_forms.py
  zds/member/tests/views/tests_admin.py
  zds/member/tests/views/tests_login.py
  zds/member/urls.py
  zds/member/views/login.py
  zds/settings/abstract_base/django.py
  zds/utils/tokens.py
Labels: C-Back, S-Refactorisation

#6354 Premier jalon pour la classification par objectif des contenus
  fixtures/goals.yaml
  templates/tutorialv2/events/descriptions.part.html
  templates/tutorialv2/includes/editorialization.part.html
  zds/tutorialv2/admin.py
  zds/tutorialv2/migrations/0034_goals.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/models/events.py
  zds/tutorialv2/models/goals.py
  zds/tutorialv2/signals.py
  zds/tutorialv2/tests/factories.py
  zds/tutorialv2/tests/tests_views/tests_editgoals.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/display.py
  zds/tutorialv2/views/goals.py
Labels: C-Back

#6356 N'envoie pas de MP lors de la dépublication de contenu sans auteur inscrit
  zds/mp/models.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/views/validations_contents.py
  zds/tutorialv2/views/validations_opinions.py
Labels: S-BUG, C-Back

#6364 Corrige une erreur lors de l'affichage de l'API
  templates/drf-yasg/swagger-ui.html
Labels: Bloquant
