Repository zestedesavoir/zds-site, pull requests merged in 2022-02, with the labels that each got.

#6230 Mise à jour triviale des dépendances Node.js
  package.json
  yarn.lock
Labels: C-Front

#6190 Ajoute des tests et refactorise AddSuggestion
  zds/tutorialv2/tests/tests_views/tests_addsuggestion.py
  zds/tutorialv2/views/editorialization.py
Labels: C-Back, hacktoberfest-accepted

#6248 Supprime l'ancien module de recherche
  zds/search/constant.py
  zds/search/forms.py
Labels: C-Search
