Repository zestedesavoir/zds-site, pull requests merged in 2022-03, with the labels that each got.

#6188 Ajoute des tests et refactorise RemoveSuggestion
  zds/tutorialv2/forms.py
  zds/tutorialv2/tests/tests_views/tests_removesuggestion.py
  zds/tutorialv2/views/editorialization.py
Labels: C-Back, hacktoberfest-accepted

#6197 Flag les features d'export pour les billets
  doc/source/back-end/contents.rst
  zds/settings/abstract_base/zds.py
  zds/tutorialv2/publication_utils.py
Labels: hacktoberfest-accepted

#6262 Remplace notre implémentation de PermissionRequiredMixin par celle de Django
  zds/member/decorator.py
  zds/member/views/emailproviders.py
  zds/member/views/hats.py
  zds/member/views/reports.py
  zds/tutorialv2/views/comments.py
  zds/tutorialv2/views/editorialization.py
  zds/tutorialv2/views/validations_contents.py
  zds/tutorialv2/views/validations_opinions.py
Labels: C-Back, S-Refactorisation

#6256 Mise à jour triviale des dépendances Python
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
Labels: C-Back

#6257 Mise à jour de python-slugify et django-uuslug
  requirements.txt
Labels: C-Back

#6258 Mise à jour de Selenium, geckodriver et OpenJDK
  doc/source/utils/selenium.rst
  requirements-dev.txt
  scripts/define_variable.sh
  scripts/dependencies/ubuntu.txt
  scripts/install_zds.sh
Labels: C-DevelopmentEnv

#6260 Mise à jour de coverage et coveralls
  .github/workflows/ci.yml
  requirements-ci.txt
Labels: C-DevelopmentEnv

#6261 Mise à jour des dépendances front
  .eslintignore
  Gulpfile.js
  assets/js/ajax-actions.js
  assets/js/autocompletion.js
  assets/js/charts.js
  assets/js/content-publication-readiness.js
  assets/js/dropdown-menu.js
  assets/js/editor-new.js
  assets/js/featured-request-ignore.js
  assets/js/featured-resource-preview.js
  assets/js/form-email-username.js
  assets/js/gallery.js
  assets/js/jquery-tabbable.js
  assets/js/karma.js
  assets/js/keyboard-navigation.js
  assets/js/markdown-help.js
  assets/js/mobile-menu.js
  assets/js/snow.js
  assets/js/spoiler.js
  assets/js/submit-dbclick.js
  assets/js/tab-modalize.js
  assets/js/topic-suggest.js
  assets/js/tribune-pick.js
  assets/js/userprofile-bio.js
  assets/js/zen-mode.js
  package.json
  yarn.lock
Labels: C-Front, C-DevelopmentEnv

#6255 Mise à jour de pyupgrade et Black
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyproject.toml
  requirements-dev.txt
  zds/forum/models.py
  zds/forum/tests/tests_views.py
  zds/gallery/models.py
  zds/gallery/tests/factories.py
  zds/notification/tests/tests_tricky.py
  zds/searchv2/forms.py
  zds/searchv2/models.py
  zds/settings/prod.py
  zds/tutorialv2/management/commands/migrate_to_zep25.py
  zds/tutorialv2/managers.py
  zds/tutorialv2/models/versioned.py
  zds/tutorialv2/publish_container.py
  zds/tutorialv2/tests/factories.py
  zds/tutorialv2/tests/tests_views/tests_editcontentlicense.py
  zds/tutorialv2/tests/tests_views/tests_editcontenttags.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/views/beta.py
  zds/tutorialv2/views/misc.py
  zds/utils/context_processor.py
  zds/utils/forms.py
  zds/utils/management/commands/clean_tags.py
  zds/utils/management/commands/load_fixtures.py
  zds/utils/models.py
  zds/utils/templatetags/append_query_params.py
  zds/utils/templatetags/email_obfuscator.py
  zds/utils/templatetags/emarkdown.py
  zds/utils/tests/factories.py
  zds/utils/tests/test_htmldiff.py
  zds/utils/tests/tests_messages.py
  zds/utils/tokens.py
Labels: C-Back

#6264 Rend publication_watchdog plus résistant aux exceptions
  zds/tutorialv2/management/commands/publication_watchdog.py
Labels: C-Back
