Repository zestedesavoir/zds-site, pull requests merged in 2023-10, with the labels that each got.

#6533 Retire l'argument obsolète "providing_args" pour la création des signaux (préparation pour Django 4)
  zds/forum/signals.py
  zds/notification/signals.py
  zds/tutorialv2/signals.py
  zds/utils/signals.py
Labels: C-Back

#6534 Retire les usages du templatetag obsolète {% ifnotequal %} (préparation pour Django 4)
  templates/misc/pagination.part.html
  templates/misc/paginator.html
Labels: C-Back

#6539 Passage à Node.js 18 aussi dans la CI
  .github/workflows/ci.yml
  .nvmrc
Labels: hacktoberfest-accepted

#6538 Met à jour l'URL pour installer NVM
  scripts/install_zds.sh
Labels: hacktoberfest-accepted

#6536 Remplace la méthode obsolète request.is_ajax (préparation pour Django 4)
  zds/forum/utils.py
  zds/forum/views.py
  zds/member/views/hats.py
  zds/member/views/profile.py
  zds/middlewares/matomomiddleware.py
  zds/mp/views.py
  zds/tutorialv2/mixins.py
  zds/tutorialv2/views/comments.py
  zds/tutorialv2/views/containers_extracts.py
  zds/tutorialv2/views/help.py
  zds/tutorialv2/views/misc.py
  zds/utils/misc.py
Labels: hacktoberfest-accepted

#6540 Change le tri par défaut sur les listes de publications par auteur
  zds/tutorialv2/urls/urls_opinions.py
  zds/tutorialv2/views/lists.py
Labels: C-Back, hacktoberfest-accepted

#6541 Retire les usages d'une méthode obsolète de Factory Boy
  zds/member/tests/factories.py
Labels: C-Back, hacktoberfest-accepted

#6410 Passage à zmarkdown 11.3.0
  zds/tutorialv2/publication_utils.py
  zmd/package-lock.json
  zmd/package.json
Labels: hacktoberfest-accepted

#6542 Modifie l'utilisation d'assertQuerysetEqual dans un test (préparation pour Django 4)
  zds/mp/tests/tests_views.py
Labels: C-Back, hacktoberfest-accepted

#6543 Retire l'usage de default_app_config (préparation pour Django 4)
  zds/notification/__init__.py
Labels: C-Back, hacktoberfest-accepted

#6545 Améliore la page qui liste les membres utilisant la même IP
  templates/member/admin/memberip.html
  zds/member/models.py
  zds/member/utils.py
  zds/member/views/moderation.py
Labels: hacktoberfest-accepted
