Repository zestedesavoir/zds-site, pull requests merged in 2023-01, with the labels that each got.

#6448 Mise à jour des dépendances Node.js
  package.json
  yarn.lock
Labels: C-Front

#6443 Billets précédents et suivants : uniquement ceux choisis par le Staff
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/views/display.py
Labels: QA Réservée Projet Étudiants

#6440 Affiche les objectifs d'une publication dans son en-tête (et corrige un souci avec l'affichage des catégories)
  templates/tutorialv2/includes/categories.part.html
  templates/tutorialv2/includes/goals.part.html
  templates/tutorialv2/includes/tags_authors.part.html
Labels: C-Front

#6442 Corrige un détail de CSS pour la neige
  assets/js/snow.js
Labels: C-Front

#6439 Corrige l'affichage des suggestions quand certaines ne sont pas publiques
  zds/tutorialv2/admin.py
  zds/tutorialv2/migrations/0036_alter_contentsuggestion_options.py
  zds/tutorialv2/models/database.py
  zds/tutorialv2/tests/models/tests_contentsuggestion.py
  zds/tutorialv2/views/display.py
Labels: C-Back

#6452 Ajoute une commande pour lister les paquets Python à mettre à jour
  Makefile
  README.rst
  requirements-dev.txt
  requirements.txt
Labels: C-DevelopmentEnv

#6453 Ajoute une commande pour lister les paquets Node.js à mettre à jour
  Makefile
  README.rst
  package.json
  yarn.lock
Labels: C-DevelopmentEnv

#6427 Mise à jour des instructions d'installation pour macOS.
  doc/source/install/install-macos.rst
  doc/source/install/install-osx.rst
Labels: S-BUG, C-Docs, S-Refactorisation
