Repository zestedesavoir/zds-site, pull requests merged in 2024-09, with the labels that each got.

#6630 Ajout de la raison du bannissement à la connexion
  zds/member/forms.py
  zds/member/models.py
  zds/member/tests/views/tests_login.py
  zds/middlewares/setlastvisitmiddleware.py
Labels: C-Back

#6550 Permet d'écrire des billets ou articles avec une structure de tutoriel
  doc/source/back-end/contents.rst
  zds/tutorialv2/models/__init__.py
  zds/tutorialv2/models/versioned.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_routes.py
  zds/tutorialv2/urls/urls_articles.py
  zds/tutorialv2/urls/urls_opinions.py
  zds/tutorialv2/urls/urls_tutorials.py
  zds/utils/management/commands/load_fixtures.py
Labels: C-Back, hacktoberfest-accepted

#6613 Déplace la modification de la miniature dans un formulaire dédié
  assets/scss/layout/_content.scss
  templates/tutorialv2/events/descriptions.part.html
  templates/tutorialv2/includes/headline/title.part.html
  zds/tutorialv2/forms.py
  zds/tutorialv2/models/events.py
  zds/tutorialv2/signals.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_editthumbnailview.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/display/content.py
  zds/tutorialv2/views/thumbnail.py
Labels: C-Front, C-Back

#6642 Ajoute des formulaires dédiés à l'introduction et la conclusion
  templates/tutorialv2/edit/conclusion.html
  templates/tutorialv2/edit/introduction.html
  templates/tutorialv2/includes/content/content.part.html
  templates/tutorialv2/view/content.html
  zds/tutorialv2/forms.py
  zds/tutorialv2/mixins.py
  zds/tutorialv2/tests/models/tests_models.py
  zds/tutorialv2/tests/tests_front.py
  zds/tutorialv2/tests/tests_lists.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_display.py
  zds/tutorialv2/tests/tests_views/tests_editconclusionview.py
  zds/tutorialv2/tests/tests_views/tests_editintroductionview.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/utils.py
  zds/tutorialv2/views/contents.py
Labels: C-Back
