Repository zestedesavoir/zds-site, pull requests merged in 2024-03, with the labels that each got.

#6582 Corrige les pages de validation pour montrer les actions de validation
  templates/tutorialv2/includes/sidebar/validation.part.html
  templates/tutorialv2/validation/index.html
  zds/tutorialv2/tests/tests_views/tests_contentvalidationview.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/display/config.py
  zds/tutorialv2/views/display/container.py
  zds/tutorialv2/views/display/content.py
  zds/tutorialv2/views/validations_contents.py
Labels: C-Back

#6565 Ajout de boutons pour modifier l'introduction et la conclusion des contenus
  assets/scss/layout/_main.scss
  templates/tutorialv2/includes/content/content.part.html
  templates/tutorialv2/view/container.html
Labels: C-Front, C-Back

#6585 Modifie un lien pour pointer vers la vue de validation d'un contenu
  templates/tutorialv2/includes/headline/validation_info.part.html
Labels: C-Front

#6586 Permet de gérer les auteurs directement depuis la liste des auteurs
  assets/scss/components/_members.scss
  doc/source/front-end/elements-specifiques-au-site.rst
  templates/misc/member_item.part.html
  templates/tutorialv2/includes/headline/authors.part.html
  templates/tutorialv2/includes/headline/header.part.html
  templates/tutorialv2/includes/sidebar/authors_management.part.html
  templates/tutorialv2/view/content.html
  zds/tutorialv2/views/authors.py
Labels: C-Front

#6589 Supprime des fichiers et imports inutiles
  zds/tutorialv2/views/display.py
  zds/tutorialv2/views/goals.py
  zds/tutorialv2/views/validations_opinions.py
Labels: C-Back

#6429 Amélioration de la connexion via les réseaux sociaux
  zds/member/validators.py
  zds/settings/abstract_base/requirements.py
  zds/utils/misc.py
  zds/utils/tests/test_misc.py
Labels: Feedback, S-Évolution

#6591 Réorganise le module tutorialv2
  zds/tutorialv2/forms.py
  zds/tutorialv2/models/events.py
  zds/tutorialv2/tests/tests_views/tests_addcontributor.py
  zds/tutorialv2/tests/tests_views/tests_editcontentlicense.py
  zds/tutorialv2/tests/tests_views/tests_editcontenttags.py
  zds/tutorialv2/tests/tests_views/tests_removesuggestion.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/authors.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/contributors.py
  zds/tutorialv2/views/display/content.py
  zds/tutorialv2/views/help.py
  zds/tutorialv2/views/licence.py
  zds/tutorialv2/views/suggestions.py
  zds/tutorialv2/views/tags.py
Labels: C-Back, S-Refactorisation

#6590 Ajoute la modification du titre et du sous-titre d'une publication depuis une modale
  assets/scss/layout/_content.scss
  assets/scss/layout/_main.scss
  assets/scss/pages/_content-editor.scss
  templates/tutorialv2/includes/headline/header.part.html
  templates/tutorialv2/includes/headline/title.part.html
  zds/tutorialv2/forms.py
  zds/tutorialv2/tests/factories.py
  zds/tutorialv2/tests/tests_opinion_views.py
  zds/tutorialv2/tests/tests_views/tests_content.py
  zds/tutorialv2/tests/tests_views/tests_edgecases.py
  zds/tutorialv2/tests/tests_views/tests_editsubtitle.py
  zds/tutorialv2/tests/tests_views/tests_edittitle.py
  zds/tutorialv2/tests/tests_views/tests_published.py
  zds/tutorialv2/urls/urls_contents.py
  zds/tutorialv2/views/contents.py
  zds/tutorialv2/views/display/config.py
  zds/tutorialv2/views/display/content.py
Labels: C-Front, C-Back
